# A sample Gemfile
source "https://rubygems.org"

gem "rails"
gem 'xml-simple'
gem 'rest-client'
gem 'bundle'
gem 'rake'
gem 'ffi'
gem 'em-proxy'
gem 'nokogiri'
gem 'rgl'
gem 'activerecord-jdbcmysql-adapter'
gem 'activerecord-jdbc-adapter'
gem 'twitter-bootstrap-rails'

